/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActualizarKmModal: typeof import('./src/components/modals/ActualizarKmModal.vue')['default']
    CargaCSV: typeof import('./src/components/CargaCSV.vue')['default']
    FormularioIngreso: typeof import('./src/components/operaciones/FormularioOperaciones.vue')['default']
    FormularioOperaciones: typeof import('./src/components/operaciones/FormularioOperaciones.vue')['default']
    FormularioVehiculo: typeof import('./src/components/vehiculos/FormularioVehiculo.vue')['default']
    ModalGlobal: typeof import('./src/components/modals/ModalGlobal.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPagination: typeof import('naive-ui')['NPagination']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NStatistic: typeof import('naive-ui')['NStatistic']
    OperacionDetails: typeof import('./src/components/operaciones/OperacionDetails.vue')['default']
    OperacionTable: typeof import('./src/components/operaciones/OperacionTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    VehiculoDetails: typeof import('./src/components/vehiculos/VehiculoDetails.vue')['default']
    VehiculoTable: typeof import('./src/components/vehiculos/VehiculoTable.vue')['default']
  }
}
