# Generated by Django 4.2.21 on 2025-05-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCombustible', models.IntegerField()),
                ('cantidadGalon', models.IntegerField(default=0)),
                ('costoGalon', models.FloatField(default=0.0)),
                ('costoTotal', models.FloatField(default=0.0)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMantenim', models.IntegerField()),
                ('costoTotal', models.FloatField(default=0.0)),
                ('comentario', models.TextField()),
                ('tipoRepuesto', models.CharField(choices=[('REP1', 'REPUESTO 1'), ('REP2', 'REPUESTO 2')], max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idServicio', models.IntegerField()),
                ('RUC', models.CharField(max_length=11)),
                ('proveedor', models.CharField(max_length=6)),
                ('tipoServicio', models.CharField(choices=[('SERV1', 'SERVICIO 1'), ('SERV2', 'SERVICIO 2')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tarjetaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('anio', models.IntegerField(default=0)),
                ('kilometraje', models.FloatField(default=0.0)),
                ('costo', models.FloatField(default=0.0)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tarjetaVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.tarjetavehiculo')),
            ],
        ),
    ]
