# Generated by Django 5.2.1 on 2025-05-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(blank=True, max_length=20, null=True)),
                ('rucProveedor', models.CharField(blank=True, max_length=11, null=True)),
                ('nombreProveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoOperacion', models.CharField(choices=[('combustible', 'Combustible'), ('mantenimiento', 'Mantenimiento'), ('servicio', 'Servicio')], max_length=15)),
                ('fecha', models.DateField(blank=True, default=None, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRepuesto', models.IntegerField()),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tarjetaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('anio_fabricacion', models.PositiveIntegerField()),
                ('anio_modelo', models.PositiveIntegerField()),
                ('motor', models.CharField(max_length=20)),
                ('combustible', models.CharField(choices=[('GSL', 'GASOLINA'), ('PET', 'PETROLEO')], max_length=10)),
                ('forma_rodante', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=30, unique=True)),
                ('serie_chasis', models.CharField(max_length=30)),
                ('ejes', models.PositiveIntegerField()),
                ('ruedas', models.PositiveIntegerField()),
                ('pasajeros', models.PositiveIntegerField()),
                ('carroceria', models.CharField(max_length=20)),
                ('peso_neto', models.DecimalField(decimal_places=3, max_digits=6)),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=6)),
                ('carga_util', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cilindrada', models.PositiveIntegerField()),
                ('cilindros', models.PositiveIntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=4)),
                ('longitud', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMantenim', models.IntegerField()),
                ('descripcionItem', models.CharField(default='', max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('costoUnitario', models.FloatField(default=0.0)),
                ('subTotal', models.FloatField(default=0.0)),
                ('operacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_detalle', to='core_app.operaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idServicio', models.IntegerField()),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('costo', models.FloatField(default=0.0)),
                ('operacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_detalle', to='core_app.operaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('anio', models.IntegerField(default=0)),
                ('kilometraje', models.FloatField(default=0.0)),
                ('costo', models.FloatField(default=0.0)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tarjetaVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.tarjetavehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCombustible', models.IntegerField()),
                ('cantidadGalones', models.IntegerField(default=0)),
                ('costoPorGalon', models.FloatField(default=0.0)),
                ('subTotal', models.FloatField(default=0.0)),
                ('operacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_detalle', to='core_app.operaciones')),
                ('placaVehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_vehiculo', to='core_app.vehiculo')),
            ],
        ),
    ]
