# Generated by Django 5.2.1 on 2025-07-16 22:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'RUC debe tener 11 dígitos.')])),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core_app.empresa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('ruc_proveedor', models.CharField(blank=True, max_length=11, null=True)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_operacion', models.CharField(choices=[('combustible', 'Combustible'), ('mantenimiento', 'Mantenimiento'), ('servicio', 'Servicio')], max_length=15)),
                ('fecha', models.DateField(blank=True, default=None, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='core_app.empresa')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='core_app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='6 caracteres, letras en mayúscula y dígitos.', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'La placa debe tener 6 caracteres alfanuméricos en mayúscula.')])),
                ('anio', models.PositiveIntegerField(default=2000, help_text='Año de matriculación, entre 1900 y 2100.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('kilometraje', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Kilómetros recorridos, 1 decimal.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del vehículo en soles, 2 decimales.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación actual (opcional).', max_length=100)),
                ('categoria', models.CharField(default='', help_text='Categoría del vehículo', max_length=50)),
                ('marca', models.CharField(default='', help_text='Marca del vehículo', max_length=50)),
                ('modelo', models.CharField(default='', help_text='Modelo del vehículo', max_length=50)),
                ('version', models.CharField(blank=True, default='', help_text='Versión del vehículo', max_length=50)),
                ('color', models.CharField(blank=True, default='', help_text='Color del vehículo', max_length=30)),
                ('anio_fabricacion', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('anio_modelo', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('motor', models.CharField(blank=True, max_length=30)),
                ('combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIÉSEL', 'Diésel'), ('ELÉCTRICO', 'Eléctrico')], default='GASOLINA', max_length=20)),
                ('forma_rodante', models.CharField(default='', max_length=50)),
                ('vin', models.CharField(default='', help_text='17 caracteres alfanuméricos (sin I,O,Q).', max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$', 'VIN inválido.')])),
                ('serie_chasis', models.CharField(blank=True, max_length=30)),
                ('ejes', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('ruedas', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)])),
                ('pasajeros', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('carroceria', models.CharField(blank=True, max_length=30)),
                ('peso_neto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('carga_util', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('cilindrada', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('cilindros', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('altura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('longitud', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='core_app.empresa')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_item', models.CharField(default='', max_length=100)),
                ('costo_servicio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core_app.empresa')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_detalle', to='core_app.operaciones')),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_vehiculo', to='core_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_item', models.CharField(default='', max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='core_app.empresa')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_detalle', to='core_app.operaciones')),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_vehiculo', to='core_app.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_galones', models.IntegerField(default=0)),
                ('costo_por_galon', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustibles', to='core_app.empresa')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_detalle', to='core_app.operaciones')),
                ('placa_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_vehiculo', to='core_app.vehiculo')),
            ],
        ),
    ]
