# Generated by Django 5.2.1 on 2025-05-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRepuesto', models.IntegerField()),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='costoTotal',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('COMBUSTIBLE', 'Combustible'), ('MANTENIMIENTO', 'Mantenimiento'), ('SERVICIO', 'Servicio')], max_length=15)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
                ('costo_total', models.FloatField(default=0.0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='core_app.vehiculo')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha_operacion'],
            },
        ),
        migrations.AddField(
            model_name='combustible',
            name='operacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_detalle', to='core_app.operaciones'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='operacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_detalle', to='core_app.operaciones'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='operacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_detalle', to='core_app.operaciones'),
        ),
    ]
