# Generated by Django 5.2.1 on 2025-05-31 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operaciones',
            name='objeto_id',
        ),
    ]
