# Generated by Django 5.2.1 on 2025-05-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_remove_operaciones_objeto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='placaVehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_vehiculo', to='core_app.vehiculo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='placaVehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_vehiculo', to='core_app.vehiculo'),
        ),
    ]
