# Generated by Django 5.2.1 on 2025-08-28 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_vehiculo_options_vehiculo_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operaciones',
            options={'ordering': ['-created_at'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AddField(
            model_name='operaciones',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
