# Generated by Django 5.2.1 on 2025-07-18 06:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Kilómetros recorridos, 1 decimal.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
