# Generated by Django 5.2.1 on 2025-08-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_operaciones_options_operaciones_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operaciones',
            options={'ordering': ['created_at'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
    ]
