# Generated by Django 5.2.1 on 2025-06-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_mantenimiento_placavehiculo_servicio_placavehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combustible',
            name='idCombustible',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='idMantenim',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='idServicio',
        ),
    ]
