# Generated by Django 5.2.1 on 2025-06-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_remove_combustible_idcombustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_detalle', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_detalle', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_detalle', to='core_app.operaciones'),
        ),
    ]
