# Generated by Django 5.2.1 on 2025-08-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_operaciones_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operaciones',
            options={'ordering': ['-created_at'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
    ]
