# Generated by Django 5.2.1 on 2025-07-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
