# Generated by Django 5.2.1 on 2025-07-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_rename_nombre_repuesto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion_item',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.repuesto'),
        ),
    ]
