# Generated by Django 5.2.1 on 2025-07-30 05:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_mantenimiento_descripcion_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='costo_servicio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='combustible',
            name='ubicacion',
            field=models.CharField(choices=[('AREQUIPA', 'Arequipa'), ('PEDREGAL', 'Pedregal'), ('CHUQUIBAMBA', 'Chuquibamba'), ('COTAWASI', 'Cotawasi'), ('MINA', 'Mina')], default='AREQUIPA', help_text='Lugar donde se realizó el repostaje', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
