# Generated by Django 5.2.1 on 2025-07-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_remove_servicio_costo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustibles', to='core_app.empresa'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='core_app.empresa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core_app.empresa'),
        ),
    ]
