# Generated by Django 5.2.1 on 2025-06-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_alter_combustible_operacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='descripcion',
            new_name='descripcionItem',
        ),
    ]
