# Generated by Django 5.2.1 on 2025-06-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_rename_descripcion_servicio_descripcionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combustible',
            old_name='cantidadGalones',
            new_name='cantidad_galones',
        ),
        migrations.RenameField(
            model_name='combustible',
            old_name='placaVehiculo',
            new_name='placa_vehiculo',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='descripcionItem',
            new_name='descripcion_item',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='placaVehiculo',
            new_name='placa_vehiculo',
        ),
        migrations.RenameField(
            model_name='operaciones',
            old_name='nombreProveedor',
            new_name='nombre_proveedor',
        ),
        migrations.RenameField(
            model_name='operaciones',
            old_name='numeroDocumento',
            new_name='numero_documento',
        ),
        migrations.RenameField(
            model_name='operaciones',
            old_name='rucProveedor',
            new_name='ruc_proveedor',
        ),
        migrations.RenameField(
            model_name='operaciones',
            old_name='tipoOperacion',
            new_name='tipo_operacion',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='descripcionItem',
            new_name='descripcion_item',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='placaVehiculo',
            new_name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='costoPorGalon',
        ),
        migrations.RemoveField(
            model_name='combustible',
            name='subTotal',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='costoUnitario',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='subTotal',
        ),
        migrations.AddField(
            model_name='combustible',
            name='costo_por_galon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='combustible',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
