# Generated by Django 5.2.1 on 2025-07-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_alter_combustible_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='core_app.empresa'),
        ),
    ]
