# Generated by Django 5.2.1 on 2025-06-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_rename_cantidadgalones_combustible_cantidad_galones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='costo',
            new_name='costo_servicio',
        ),
    ]
