# Generated by Django 5.2.1 on 2025-07-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_repuesto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustibles', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core_app.operaciones'),
        ),
    ]
