# Generated by Django 5.2.1 on 2025-07-30 12:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_combustible_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustible_detalle', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_detalle', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_detalle', to='core_app.operaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
