# Generated by Django 5.2.1 on 2025-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_rename_costo_servicio_costo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
