# Generated by Django 5.2.1 on 2025-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_operaciones_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
