# Generated by Django 5.2.1 on 2025-06-09 00:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_vehiculo_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tarjetaVehiculo',
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio_modelo',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carga_util',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carroceria',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(default='', help_text='Categoría del vehículo', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cilindros',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Color del vehículo', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico')], default='GASOLINA', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ejes',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='forma_rodante',
            field=models.CharField(choices=[('NEUMATICA', 'Neumática'), ('ACERO', 'Acero'), ('MIXTA', 'Mixta')], default='NEUMATICA', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='longitud',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='', help_text='Marca del vehículo', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default='', help_text='Modelo del vehículo', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='pasajeros',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_neto',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ruedas',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='serie_chasis',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='version',
            field=models.CharField(blank=True, default='', help_text='Versión del vehículo', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(default='', help_text='17 caracteres alfanuméricos (sin I,O,Q).', max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[A-HJ-NPR-Z0-9]{17}$', 'VIN inválido.')]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(default=2000, help_text='Año de matriculación, entre 1900 y 2100.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del vehículo en soles, 2 decimales.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Kilómetros recorridos, 1 decimal.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(help_text='6 caracteres, letras en mayúscula y dígitos.', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'La placa debe tener 6 caracteres alfanuméricos en mayúscula.')]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación actual (opcional).', max_length=100),
        ),
        migrations.DeleteModel(
            name='tarjetaVehiculo',
        ),
    ]
