# Generated by Django 5.2.1 on 2025-06-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_remove_vehiculo_tarjetavehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='forma_rodante',
            field=models.CharField(default='', max_length=50),
        ),
    ]
