# Generated by Django 5.2.1 on 2025-06-14 04:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_alter_vehiculo_forma_rodante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
