# Generated by Django 5.2.1 on 2025-06-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_alter_vehiculo_cilindrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIÉSEL', 'Diésel'), ('ELÉCTRICO', 'Eléctrico')], default='GASOLINA', max_length=20),
        ),
    ]
